
[[extend]]
path = "./examples/lanitra-manga/Makefile.toml"

[config]
default_to_workspace = false

[tasks.clippy]
command = "cargo"
args = ["clippy", "--workspace"]

[tasks.doc]
command = "cargo"
args = ["doc", "--workspace"]

[tasks.fetch]
command = "cargo"
args = ["fetch"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy-clean]
dependencies = ["clippy", "clean"]

[tasks.publish-ts-transport]
command = "pnpm"
args = ["publish", "packages/kanamaru-transport"]

[tasks.publish-core]
command = "cargo"
args = ["publish", "-p", "kanamaru"]

[tasks.publish-build]
command = "cargo"
args = ["publish", "-p", "kanamaru-build"]

[tasks.run-example-1]
command = "pnpm"
args = ["tauri", "dev"]
cwd = "./examples/example-1"

[tasks.run-lanitra-manga]
command = "pnpm"
args = ["tauri", "dev"]
cwd = "./examples/lanitra-manga"

[tasks.build-transport]
command = "pnpm"
args = ["build"]
cwd = "./packages/kanamaru-transport"
