[package]
name = "lanitra-manga-rpc"
version = "0.1.0"
edition = "2021"
authors.workspace = true
links = "lanitra-manga"

[build-dependencies]
kanamaru-build = { workspace = true, default-features = false, features = [
    "tauri",
] }
anyhow.workspace = true

[dependencies]
kanamaru.workspace = true
tauri = { workspace = true, default-features = false }
serde_json.workspace = true
prost.workspace = true
serde.workspace = true
prost-types = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-stream.workspace = true
async-stream = "0.3.6"
bsky-sdk = { workspace = true }
atrium-api = { workspace = true }
reqwest = { workspace = true }
time = "0.3.37"
chrono = "0.4.39"
atrium-xrpc-client = { version = "0.5.11", default-features = false, features = [
    "reqwest",
] }
lanitra-manga-commons = { path = "../crates/commons" }
lanitra-manga-profiles = { path = "../crates/profiles" }
lanitra-manga-posts = { path = "../crates/posts" }
lanitra-manga-feeds = { path = "../crates/feeds" }
derive_more = { version = "2.0.1", features = [
    "constructor",
    "deref",
    "deref_mut",
    "from",
] }
tower = { workspace = true, features = ["limit", "buffer"] }
duration-string = { version = "0.5", features = ["serde"] }
