syntax = "proto3";

import "commons.proto";
import "profiles.proto";

package mg.tonymushah.lanitra_manga.posts.view;

message ViewImage {
    string fullsize = 1;
    string thumb = 2;
    string alt = 3;
    optional mg.tonymushah.lanitra_manga.commons.AspectRatio ratio = 4;
}

message ViewImages {
    repeated ViewImage images = 1;
}

message ViewVideo {
    optional string alt = 1;
    string cid = 2;
    string playlist = 3;
    optional string thumbnail = 4;
    optional mg.tonymushah.lanitra_manga.commons.AspectRatio ratio = 5; 
}

message ViewExternal {
    string description = 1;
    string title = 2;
    string uri = 3;
    optional string thumb = 4;
}

message PostViewMessage {
    string cid = 1;
    string uri = 2;
    mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author = 3;
    optional int64 like_count = 4;
    optional int64 quote_count = 5;
    optional int64 reply_count = 6;
    optional int64 repost_cound = 7;
    string indexed_at = 8;
    optional mg.tonymushah.lanitra_manga.commons.RichTextDetails content = 9;
    oneof embed {
        ViewImages images = 10;
        ViewVideo video = 11;
        ViewExternal external = 12;
        mg.tonymushah.lanitra_manga.commons.Empty others = 13;
    }
}

message ViewPostThreadRequest {
    string uri = 1;
    optional uint32 depth = 2;
    optional uint32 parent_height = 3;
}

message NotFoundPost {
    string uri = 1;
    bool not_found = 2;
}

message BlockedPost{
    string uri = 1;
    bool blocked = 2;
    string author_did = 3;
}

message ThreadViewPostInner {
    oneof actual_post {
        TheardViewPost post = 1;
        NotFoundPost not_found = 2;
        BlockedPost blocked_post = 3;
    }
}

message TheardViewPost {
    optional ThreadViewPostInner parent = 1;
    PostViewMessage post = 2;
    repeated ThreadViewPostInner replies = 3;
}

message ViewThreadResponse {
    ThreadViewPostInner thread = 1;
}

message ViewPostsRequest {
    repeated string uri = 1;
}

message ViewPostsResponse {
    repeated PostViewMessage posts = 1;
}

service PostViews {
    rpc viewPostThread (ViewPostThreadRequest) returns (ViewThreadResponse);
    rpc getPosts (ViewPostsRequest) returns (ViewPostsResponse);
}

message ReplyRefMessage {
    ThreadViewPostInner root = 1;
    ThreadViewPostInner parent = 2;
    optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author = 3;
}