[package]
name = "lanitra-manga-commons"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[build-dependencies]
lanitra-manga-proto-build.workspace = true

[dependencies]
kanamaru = { workspace = true }
prost = { workspace = true }
bsky-sdk = { workspace = true }
atrium-api = { workspace = true }
thiserror = { workspace = true }
cid = { workspace = true }
