[package]
name = "lanitra-manga-posts"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[build-dependencies]
kanamaru-build = { workspace = true, default-features = false, features = [
    "prost",
] }

[dependencies]
kanamaru = { workspace = true }
prost = { workspace = true }
lanitra-manga-commons = { path = "../commons" }
lanitra-manga-profiles = { path = "../profiles" }
