syntax = "proto3";

package mg.tonymushah.kanamaru.example1;

import "commons.proto";

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string response = 1;
}

service HelloService {
    rpc sayHello(HelloRequest) returns (HelloResponse);
    rpc listenToHellos(mg.tonymushah.kanamaru.Empty) returns (stream HelloResponse);
    rpc sayHellos(stream HelloRequest) returns (mg.tonymushah.kanamaru.Empty);
    rpc sayHelloWithResponses(stream HelloRequest) returns (stream HelloResponse);
}