// @generated by protobuf-ts 2.9.6 with parameter server_none
// @generated from protobuf file "posts/view.proto" (package "mg.tonymushah.lanitra_manga.posts.view", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostViews } from "./view";
import type { ViewPostsResponse } from "./view";
import type { ViewPostsRequest } from "./view";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ViewThreadResponse } from "./view";
import type { ViewPostThreadRequest } from "./view";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.posts.view.PostViews
 */
export interface IPostViewsClient {
    /**
     * @generated from protobuf rpc: viewPostThread(mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest) returns (mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse);
     */
    viewPostThread(input: ViewPostThreadRequest, options?: RpcOptions): UnaryCall<ViewPostThreadRequest, ViewThreadResponse>;
    /**
     * @generated from protobuf rpc: getPosts(mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest) returns (mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse);
     */
    getPosts(input: ViewPostsRequest, options?: RpcOptions): UnaryCall<ViewPostsRequest, ViewPostsResponse>;
}
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.posts.view.PostViews
 */
export class PostViewsClient implements IPostViewsClient, ServiceInfo {
    typeName = PostViews.typeName;
    methods = PostViews.methods;
    options = PostViews.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: viewPostThread(mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest) returns (mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse);
     */
    viewPostThread(input: ViewPostThreadRequest, options?: RpcOptions): UnaryCall<ViewPostThreadRequest, ViewThreadResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ViewPostThreadRequest, ViewThreadResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: getPosts(mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest) returns (mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse);
     */
    getPosts(input: ViewPostsRequest, options?: RpcOptions): UnaryCall<ViewPostsRequest, ViewPostsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ViewPostsRequest, ViewPostsResponse>("unary", this._transport, method, opt, input);
    }
}
