// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "posts/view.proto" (package "mg.tonymushah.lanitra_manga.posts.view", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ProfileViewBasic } from "../profiles";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewMessage
 */
export interface PostViewMessage {
    /**
     * @generated from protobuf field: string cid = 1;
     */
    cid: string;
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author = 3;
     */
    author?: ProfileViewBasic;
    /**
     * @generated from protobuf field: optional int64 like_count = 4;
     */
    likeCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 quote_count = 5;
     */
    quoteCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 reply_count = 6;
     */
    replyCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 repost_cound = 7;
     */
    repostCound?: bigint;
    /**
     * @generated from protobuf field: string indexed_at = 8;
     */
    indexedAt: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest
 */
export interface ViewPostThreadRequest {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: optional uint32 depth = 2;
     */
    depth?: number;
    /**
     * @generated from protobuf field: optional uint32 parent_height = 3;
     */
    parentHeight?: number;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.NotFoundPost
 */
export interface NotFoundPost {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: bool not_found = 2;
     */
    notFound: boolean;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.BlockedPost
 */
export interface BlockedPost {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: bool blocked = 2;
     */
    blocked: boolean;
    /**
     * @generated from protobuf field: string author_did = 3;
     */
    authorDid: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner
 */
export interface ThreadViewPostInner {
    /**
     * @generated from protobuf oneof: actual_post
     */
    actualPost: {
        oneofKind: "post";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post = 1;
         */
        post: TheardViewPost;
    } | {
        oneofKind: "notFound";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found = 2;
         */
        notFound: NotFoundPost;
    } | {
        oneofKind: "blockedPost";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post = 3;
         */
        blockedPost: BlockedPost;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.TheardViewPost
 */
export interface TheardViewPost {
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 1;
     */
    parent?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2;
     */
    post?: PostViewMessage;
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies = 3;
     */
    replies: ThreadViewPostInner[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse
 */
export interface ViewThreadResponse {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.TheardViewPost thread = 1;
     */
    thread?: TheardViewPost;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest
 */
export interface ViewPostsRequest {
    /**
     * @generated from protobuf field: repeated string uri = 1;
     */
    uri: string[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse
 */
export interface ViewPostsResponse {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts = 1;
     */
    posts: PostViewMessage[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage
 */
export interface ReplyRefMessage {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root = 1;
     */
    root?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 2;
     */
    parent?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author = 3;
     */
    grandparentAuthor?: ProfileViewBasic;
}
// @generated message type with reflection information, may provide speed optimized methods
class PostViewMessage$Type extends MessageType<PostViewMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.PostViewMessage", [
            { no: 1, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "author", kind: "message", T: () => ProfileViewBasic },
            { no: 4, name: "like_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "quote_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "reply_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "repost_cound", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "indexed_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PostViewMessage>): PostViewMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.uri = "";
        message.indexedAt = "";
        if (value !== undefined)
            reflectionMergePartial<PostViewMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostViewMessage): PostViewMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cid */ 1:
                    message.cid = reader.string();
                    break;
                case /* string uri */ 2:
                    message.uri = reader.string();
                    break;
                case /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author */ 3:
                    message.author = ProfileViewBasic.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                case /* optional int64 like_count */ 4:
                    message.likeCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 quote_count */ 5:
                    message.quoteCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 reply_count */ 6:
                    message.replyCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 repost_cound */ 7:
                    message.repostCound = reader.int64().toBigInt();
                    break;
                case /* string indexed_at */ 8:
                    message.indexedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostViewMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cid = 1; */
        if (message.cid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cid);
        /* string uri = 2; */
        if (message.uri !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uri);
        /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author = 3; */
        if (message.author)
            ProfileViewBasic.internalBinaryWrite(message.author, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional int64 like_count = 4; */
        if (message.likeCount !== undefined)
            writer.tag(4, WireType.Varint).int64(message.likeCount);
        /* optional int64 quote_count = 5; */
        if (message.quoteCount !== undefined)
            writer.tag(5, WireType.Varint).int64(message.quoteCount);
        /* optional int64 reply_count = 6; */
        if (message.replyCount !== undefined)
            writer.tag(6, WireType.Varint).int64(message.replyCount);
        /* optional int64 repost_cound = 7; */
        if (message.repostCound !== undefined)
            writer.tag(7, WireType.Varint).int64(message.repostCound);
        /* string indexed_at = 8; */
        if (message.indexedAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.indexedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewMessage
 */
export const PostViewMessage = new PostViewMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostThreadRequest$Type extends MessageType<ViewPostThreadRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "depth", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "parent_height", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ViewPostThreadRequest>): ViewPostThreadRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<ViewPostThreadRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostThreadRequest): ViewPostThreadRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* optional uint32 depth */ 2:
                    message.depth = reader.uint32();
                    break;
                case /* optional uint32 parent_height */ 3:
                    message.parentHeight = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostThreadRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* optional uint32 depth = 2; */
        if (message.depth !== undefined)
            writer.tag(2, WireType.Varint).uint32(message.depth);
        /* optional uint32 parent_height = 3; */
        if (message.parentHeight !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.parentHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest
 */
export const ViewPostThreadRequest = new ViewPostThreadRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotFoundPost$Type extends MessageType<NotFoundPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.NotFoundPost", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "not_found", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotFoundPost>): NotFoundPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.notFound = false;
        if (value !== undefined)
            reflectionMergePartial<NotFoundPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotFoundPost): NotFoundPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* bool not_found */ 2:
                    message.notFound = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotFoundPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* bool not_found = 2; */
        if (message.notFound !== false)
            writer.tag(2, WireType.Varint).bool(message.notFound);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.NotFoundPost
 */
export const NotFoundPost = new NotFoundPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockedPost$Type extends MessageType<BlockedPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.BlockedPost", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "blocked", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "author_did", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BlockedPost>): BlockedPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.blocked = false;
        message.authorDid = "";
        if (value !== undefined)
            reflectionMergePartial<BlockedPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockedPost): BlockedPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* bool blocked */ 2:
                    message.blocked = reader.bool();
                    break;
                case /* string author_did */ 3:
                    message.authorDid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlockedPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* bool blocked = 2; */
        if (message.blocked !== false)
            writer.tag(2, WireType.Varint).bool(message.blocked);
        /* string author_did = 3; */
        if (message.authorDid !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.authorDid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.BlockedPost
 */
export const BlockedPost = new BlockedPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ThreadViewPostInner$Type extends MessageType<ThreadViewPostInner> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner", [
            { no: 1, name: "post", kind: "message", oneof: "actualPost", T: () => TheardViewPost },
            { no: 2, name: "not_found", kind: "message", oneof: "actualPost", T: () => NotFoundPost },
            { no: 3, name: "blocked_post", kind: "message", oneof: "actualPost", T: () => BlockedPost }
        ]);
    }
    create(value?: PartialMessage<ThreadViewPostInner>): ThreadViewPostInner {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.actualPost = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ThreadViewPostInner>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ThreadViewPostInner): ThreadViewPostInner {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post */ 1:
                    message.actualPost = {
                        oneofKind: "post",
                        post: TheardViewPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).post)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found */ 2:
                    message.actualPost = {
                        oneofKind: "notFound",
                        notFound: NotFoundPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).notFound)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post */ 3:
                    message.actualPost = {
                        oneofKind: "blockedPost",
                        blockedPost: BlockedPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).blockedPost)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ThreadViewPostInner, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post = 1; */
        if (message.actualPost.oneofKind === "post")
            TheardViewPost.internalBinaryWrite(message.actualPost.post, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found = 2; */
        if (message.actualPost.oneofKind === "notFound")
            NotFoundPost.internalBinaryWrite(message.actualPost.notFound, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post = 3; */
        if (message.actualPost.oneofKind === "blockedPost")
            BlockedPost.internalBinaryWrite(message.actualPost.blockedPost, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner
 */
export const ThreadViewPostInner = new ThreadViewPostInner$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TheardViewPost$Type extends MessageType<TheardViewPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.TheardViewPost", [
            { no: 1, name: "parent", kind: "message", T: () => ThreadViewPostInner },
            { no: 2, name: "post", kind: "message", T: () => PostViewMessage },
            { no: 3, name: "replies", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ThreadViewPostInner }
        ]);
    }
    create(value?: PartialMessage<TheardViewPost>): TheardViewPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.replies = [];
        if (value !== undefined)
            reflectionMergePartial<TheardViewPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TheardViewPost): TheardViewPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent */ 1:
                    message.parent = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.parent);
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post */ 2:
                    message.post = PostViewMessage.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies */ 3:
                    message.replies.push(ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TheardViewPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 1; */
        if (message.parent)
            ThreadViewPostInner.internalBinaryWrite(message.parent, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2; */
        if (message.post)
            PostViewMessage.internalBinaryWrite(message.post, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies = 3; */
        for (let i = 0; i < message.replies.length; i++)
            ThreadViewPostInner.internalBinaryWrite(message.replies[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.TheardViewPost
 */
export const TheardViewPost = new TheardViewPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewThreadResponse$Type extends MessageType<ViewThreadResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse", [
            { no: 1, name: "thread", kind: "message", T: () => TheardViewPost }
        ]);
    }
    create(value?: PartialMessage<ViewThreadResponse>): ViewThreadResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ViewThreadResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewThreadResponse): ViewThreadResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost thread */ 1:
                    message.thread = TheardViewPost.internalBinaryRead(reader, reader.uint32(), options, message.thread);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewThreadResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost thread = 1; */
        if (message.thread)
            TheardViewPost.internalBinaryWrite(message.thread, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse
 */
export const ViewThreadResponse = new ViewThreadResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostsRequest$Type extends MessageType<ViewPostsRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest", [
            { no: 1, name: "uri", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ViewPostsRequest>): ViewPostsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = [];
        if (value !== undefined)
            reflectionMergePartial<ViewPostsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostsRequest): ViewPostsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string uri */ 1:
                    message.uri.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string uri = 1; */
        for (let i = 0; i < message.uri.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.uri[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest
 */
export const ViewPostsRequest = new ViewPostsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostsResponse$Type extends MessageType<ViewPostsResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse", [
            { no: 1, name: "posts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostViewMessage }
        ]);
    }
    create(value?: PartialMessage<ViewPostsResponse>): ViewPostsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        if (value !== undefined)
            reflectionMergePartial<ViewPostsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostsResponse): ViewPostsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts */ 1:
                    message.posts.push(PostViewMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            PostViewMessage.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse
 */
export const ViewPostsResponse = new ViewPostsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplyRefMessage$Type extends MessageType<ReplyRefMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage", [
            { no: 1, name: "root", kind: "message", T: () => ThreadViewPostInner },
            { no: 2, name: "parent", kind: "message", T: () => ThreadViewPostInner },
            { no: 3, name: "grandparent_author", kind: "message", T: () => ProfileViewBasic }
        ]);
    }
    create(value?: PartialMessage<ReplyRefMessage>): ReplyRefMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReplyRefMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplyRefMessage): ReplyRefMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root */ 1:
                    message.root = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent */ 2:
                    message.parent = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.parent);
                    break;
                case /* optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author */ 3:
                    message.grandparentAuthor = ProfileViewBasic.internalBinaryRead(reader, reader.uint32(), options, message.grandparentAuthor);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReplyRefMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root = 1; */
        if (message.root)
            ThreadViewPostInner.internalBinaryWrite(message.root, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 2; */
        if (message.parent)
            ThreadViewPostInner.internalBinaryWrite(message.parent, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author = 3; */
        if (message.grandparentAuthor)
            ProfileViewBasic.internalBinaryWrite(message.grandparentAuthor, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage
 */
export const ReplyRefMessage = new ReplyRefMessage$Type();
/**
 * @generated ServiceType for protobuf service mg.tonymushah.lanitra_manga.posts.view.PostViews
 */
export const PostViews = new ServiceType("mg.tonymushah.lanitra_manga.posts.view.PostViews", [
    { name: "viewPostThread", options: {}, I: ViewPostThreadRequest, O: ViewThreadResponse },
    { name: "getPosts", options: {}, I: ViewPostsRequest, O: ViewPostsResponse }
]);
