// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "posts/view.proto" (package "mg.tonymushah.lanitra_manga.posts.view", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { RichTextDetails } from "../commons";
import { ProfileViewBasic } from "../profiles";
import { AspectRatio } from "../commons";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewImage
 */
export interface ViewImage {
    /**
     * @generated from protobuf field: string fullsize = 1;
     */
    fullsize: string;
    /**
     * @generated from protobuf field: string thumb = 2;
     */
    thumb: string;
    /**
     * @generated from protobuf field: string alt = 3;
     */
    alt: string;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.AspectRatio ratio = 4;
     */
    ratio?: AspectRatio;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewImages
 */
export interface ViewImages {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.ViewImage images = 1;
     */
    images: ViewImage[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewVideo
 */
export interface ViewVideo {
    /**
     * @generated from protobuf field: optional string alt = 1;
     */
    alt?: string;
    /**
     * @generated from protobuf field: string cid = 2;
     */
    cid: string;
    /**
     * @generated from protobuf field: string playlist = 3;
     */
    playlist: string;
    /**
     * @generated from protobuf field: optional string thumbnail = 4;
     */
    thumbnail?: string;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.AspectRatio ratio = 5;
     */
    ratio?: AspectRatio;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewExternal
 */
export interface ViewExternal {
    /**
     * @generated from protobuf field: string description = 1;
     */
    description: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string uri = 3;
     */
    uri: string;
    /**
     * @generated from protobuf field: optional string thumb = 4;
     */
    thumb?: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded
 */
export interface PostViewEmbeded {
    /**
     * @generated from protobuf oneof: media
     */
    media: {
        oneofKind: "images";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ViewImages images = 1;
         */
        images: ViewImages;
    } | {
        oneofKind: "video";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ViewVideo video = 2;
         */
        video: ViewVideo;
    } | {
        oneofKind: "external";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ViewExternal external = 3;
         */
        external: ViewExternal;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewMessage
 */
export interface PostViewMessage {
    /**
     * @generated from protobuf field: string cid = 1;
     */
    cid: string;
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author = 3;
     */
    author?: ProfileViewBasic;
    /**
     * @generated from protobuf field: optional int64 like_count = 4;
     */
    likeCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 quote_count = 5;
     */
    quoteCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 reply_count = 6;
     */
    replyCount?: bigint;
    /**
     * @generated from protobuf field: optional int64 repost_cound = 7;
     */
    repostCound?: bigint;
    /**
     * @generated from protobuf field: string indexed_at = 8;
     */
    indexedAt: string;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.RichTextDetails content = 9;
     */
    content?: RichTextDetails;
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded embeds = 10;
     */
    embeds: PostViewEmbeded[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest
 */
export interface ViewPostThreadRequest {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: optional uint32 depth = 2;
     */
    depth?: number;
    /**
     * @generated from protobuf field: optional uint32 parent_height = 3;
     */
    parentHeight?: number;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.NotFoundPost
 */
export interface NotFoundPost {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: bool not_found = 2;
     */
    notFound: boolean;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.BlockedPost
 */
export interface BlockedPost {
    /**
     * @generated from protobuf field: string uri = 1;
     */
    uri: string;
    /**
     * @generated from protobuf field: bool blocked = 2;
     */
    blocked: boolean;
    /**
     * @generated from protobuf field: string author_did = 3;
     */
    authorDid: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner
 */
export interface ThreadViewPostInner {
    /**
     * @generated from protobuf oneof: actual_post
     */
    actualPost: {
        oneofKind: "post";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post = 1;
         */
        post: TheardViewPost;
    } | {
        oneofKind: "notFound";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found = 2;
         */
        notFound: NotFoundPost;
    } | {
        oneofKind: "blockedPost";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post = 3;
         */
        blockedPost: BlockedPost;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.TheardViewPost
 */
export interface TheardViewPost {
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 1;
     */
    parent?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2;
     */
    post?: PostViewMessage;
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies = 3;
     */
    replies: ThreadViewPostInner[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse
 */
export interface ViewThreadResponse {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner thread = 1;
     */
    thread?: ThreadViewPostInner;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest
 */
export interface ViewPostsRequest {
    /**
     * @generated from protobuf field: repeated string uri = 1;
     */
    uri: string[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse
 */
export interface ViewPostsResponse {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts = 1;
     */
    posts: PostViewMessage[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage
 */
export interface ReplyRefMessage {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root = 1;
     */
    root?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 2;
     */
    parent?: ThreadViewPostInner;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author = 3;
     */
    grandparentAuthor?: ProfileViewBasic;
}
// @generated message type with reflection information, may provide speed optimized methods
class ViewImage$Type extends MessageType<ViewImage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewImage", [
            { no: 1, name: "fullsize", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "thumb", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "alt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "ratio", kind: "message", T: () => AspectRatio }
        ]);
    }
    create(value?: PartialMessage<ViewImage>): ViewImage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fullsize = "";
        message.thumb = "";
        message.alt = "";
        if (value !== undefined)
            reflectionMergePartial<ViewImage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewImage): ViewImage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string fullsize */ 1:
                    message.fullsize = reader.string();
                    break;
                case /* string thumb */ 2:
                    message.thumb = reader.string();
                    break;
                case /* string alt */ 3:
                    message.alt = reader.string();
                    break;
                case /* optional mg.tonymushah.lanitra_manga.AspectRatio ratio */ 4:
                    message.ratio = AspectRatio.internalBinaryRead(reader, reader.uint32(), options, message.ratio);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewImage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string fullsize = 1; */
        if (message.fullsize !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fullsize);
        /* string thumb = 2; */
        if (message.thumb !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.thumb);
        /* string alt = 3; */
        if (message.alt !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.alt);
        /* optional mg.tonymushah.lanitra_manga.AspectRatio ratio = 4; */
        if (message.ratio)
            AspectRatio.internalBinaryWrite(message.ratio, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewImage
 */
export const ViewImage = new ViewImage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewImages$Type extends MessageType<ViewImages> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewImages", [
            { no: 1, name: "images", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ViewImage }
        ]);
    }
    create(value?: PartialMessage<ViewImages>): ViewImages {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.images = [];
        if (value !== undefined)
            reflectionMergePartial<ViewImages>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewImages): ViewImages {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.ViewImage images */ 1:
                    message.images.push(ViewImage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewImages, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.view.ViewImage images = 1; */
        for (let i = 0; i < message.images.length; i++)
            ViewImage.internalBinaryWrite(message.images[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewImages
 */
export const ViewImages = new ViewImages$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewVideo$Type extends MessageType<ViewVideo> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewVideo", [
            { no: 1, name: "alt", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "playlist", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "thumbnail", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "ratio", kind: "message", T: () => AspectRatio }
        ]);
    }
    create(value?: PartialMessage<ViewVideo>): ViewVideo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.playlist = "";
        if (value !== undefined)
            reflectionMergePartial<ViewVideo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewVideo): ViewVideo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string alt */ 1:
                    message.alt = reader.string();
                    break;
                case /* string cid */ 2:
                    message.cid = reader.string();
                    break;
                case /* string playlist */ 3:
                    message.playlist = reader.string();
                    break;
                case /* optional string thumbnail */ 4:
                    message.thumbnail = reader.string();
                    break;
                case /* optional mg.tonymushah.lanitra_manga.AspectRatio ratio */ 5:
                    message.ratio = AspectRatio.internalBinaryRead(reader, reader.uint32(), options, message.ratio);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewVideo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string alt = 1; */
        if (message.alt !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.alt);
        /* string cid = 2; */
        if (message.cid !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.cid);
        /* string playlist = 3; */
        if (message.playlist !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.playlist);
        /* optional string thumbnail = 4; */
        if (message.thumbnail !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.thumbnail);
        /* optional mg.tonymushah.lanitra_manga.AspectRatio ratio = 5; */
        if (message.ratio)
            AspectRatio.internalBinaryWrite(message.ratio, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewVideo
 */
export const ViewVideo = new ViewVideo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewExternal$Type extends MessageType<ViewExternal> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewExternal", [
            { no: 1, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "thumb", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ViewExternal>): ViewExternal {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.description = "";
        message.title = "";
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<ViewExternal>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewExternal): ViewExternal {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string description */ 1:
                    message.description = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string uri */ 3:
                    message.uri = reader.string();
                    break;
                case /* optional string thumb */ 4:
                    message.thumb = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewExternal, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string description = 1; */
        if (message.description !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.description);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string uri = 3; */
        if (message.uri !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.uri);
        /* optional string thumb = 4; */
        if (message.thumb !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.thumb);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewExternal
 */
export const ViewExternal = new ViewExternal$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostViewEmbeded$Type extends MessageType<PostViewEmbeded> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded", [
            { no: 1, name: "images", kind: "message", oneof: "media", T: () => ViewImages },
            { no: 2, name: "video", kind: "message", oneof: "media", T: () => ViewVideo },
            { no: 3, name: "external", kind: "message", oneof: "media", T: () => ViewExternal }
        ]);
    }
    create(value?: PartialMessage<PostViewEmbeded>): PostViewEmbeded {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.media = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<PostViewEmbeded>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostViewEmbeded): PostViewEmbeded {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.ViewImages images */ 1:
                    message.media = {
                        oneofKind: "images",
                        images: ViewImages.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).images)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.ViewVideo video */ 2:
                    message.media = {
                        oneofKind: "video",
                        video: ViewVideo.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).video)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.ViewExternal external */ 3:
                    message.media = {
                        oneofKind: "external",
                        external: ViewExternal.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).external)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostViewEmbeded, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.ViewImages images = 1; */
        if (message.media.oneofKind === "images")
            ViewImages.internalBinaryWrite(message.media.images, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.ViewVideo video = 2; */
        if (message.media.oneofKind === "video")
            ViewVideo.internalBinaryWrite(message.media.video, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.ViewExternal external = 3; */
        if (message.media.oneofKind === "external")
            ViewExternal.internalBinaryWrite(message.media.external, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded
 */
export const PostViewEmbeded = new PostViewEmbeded$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostViewMessage$Type extends MessageType<PostViewMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.PostViewMessage", [
            { no: 1, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "author", kind: "message", T: () => ProfileViewBasic },
            { no: 4, name: "like_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "quote_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "reply_count", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "repost_cound", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "indexed_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "content", kind: "message", T: () => RichTextDetails },
            { no: 10, name: "embeds", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostViewEmbeded }
        ]);
    }
    create(value?: PartialMessage<PostViewMessage>): PostViewMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.uri = "";
        message.indexedAt = "";
        message.embeds = [];
        if (value !== undefined)
            reflectionMergePartial<PostViewMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostViewMessage): PostViewMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cid */ 1:
                    message.cid = reader.string();
                    break;
                case /* string uri */ 2:
                    message.uri = reader.string();
                    break;
                case /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author */ 3:
                    message.author = ProfileViewBasic.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                case /* optional int64 like_count */ 4:
                    message.likeCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 quote_count */ 5:
                    message.quoteCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 reply_count */ 6:
                    message.replyCount = reader.int64().toBigInt();
                    break;
                case /* optional int64 repost_cound */ 7:
                    message.repostCound = reader.int64().toBigInt();
                    break;
                case /* string indexed_at */ 8:
                    message.indexedAt = reader.string();
                    break;
                case /* optional mg.tonymushah.lanitra_manga.RichTextDetails content */ 9:
                    message.content = RichTextDetails.internalBinaryRead(reader, reader.uint32(), options, message.content);
                    break;
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded embeds */ 10:
                    message.embeds.push(PostViewEmbeded.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostViewMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cid = 1; */
        if (message.cid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cid);
        /* string uri = 2; */
        if (message.uri !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uri);
        /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic author = 3; */
        if (message.author)
            ProfileViewBasic.internalBinaryWrite(message.author, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional int64 like_count = 4; */
        if (message.likeCount !== undefined)
            writer.tag(4, WireType.Varint).int64(message.likeCount);
        /* optional int64 quote_count = 5; */
        if (message.quoteCount !== undefined)
            writer.tag(5, WireType.Varint).int64(message.quoteCount);
        /* optional int64 reply_count = 6; */
        if (message.replyCount !== undefined)
            writer.tag(6, WireType.Varint).int64(message.replyCount);
        /* optional int64 repost_cound = 7; */
        if (message.repostCound !== undefined)
            writer.tag(7, WireType.Varint).int64(message.repostCound);
        /* string indexed_at = 8; */
        if (message.indexedAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.indexedAt);
        /* optional mg.tonymushah.lanitra_manga.RichTextDetails content = 9; */
        if (message.content)
            RichTextDetails.internalBinaryWrite(message.content, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewEmbeded embeds = 10; */
        for (let i = 0; i < message.embeds.length; i++)
            PostViewEmbeded.internalBinaryWrite(message.embeds[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.PostViewMessage
 */
export const PostViewMessage = new PostViewMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostThreadRequest$Type extends MessageType<ViewPostThreadRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "depth", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "parent_height", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ViewPostThreadRequest>): ViewPostThreadRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<ViewPostThreadRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostThreadRequest): ViewPostThreadRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* optional uint32 depth */ 2:
                    message.depth = reader.uint32();
                    break;
                case /* optional uint32 parent_height */ 3:
                    message.parentHeight = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostThreadRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* optional uint32 depth = 2; */
        if (message.depth !== undefined)
            writer.tag(2, WireType.Varint).uint32(message.depth);
        /* optional uint32 parent_height = 3; */
        if (message.parentHeight !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.parentHeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostThreadRequest
 */
export const ViewPostThreadRequest = new ViewPostThreadRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotFoundPost$Type extends MessageType<NotFoundPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.NotFoundPost", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "not_found", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotFoundPost>): NotFoundPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.notFound = false;
        if (value !== undefined)
            reflectionMergePartial<NotFoundPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotFoundPost): NotFoundPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* bool not_found */ 2:
                    message.notFound = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotFoundPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* bool not_found = 2; */
        if (message.notFound !== false)
            writer.tag(2, WireType.Varint).bool(message.notFound);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.NotFoundPost
 */
export const NotFoundPost = new NotFoundPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockedPost$Type extends MessageType<BlockedPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.BlockedPost", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "blocked", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "author_did", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BlockedPost>): BlockedPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = "";
        message.blocked = false;
        message.authorDid = "";
        if (value !== undefined)
            reflectionMergePartial<BlockedPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockedPost): BlockedPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* bool blocked */ 2:
                    message.blocked = reader.bool();
                    break;
                case /* string author_did */ 3:
                    message.authorDid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlockedPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* bool blocked = 2; */
        if (message.blocked !== false)
            writer.tag(2, WireType.Varint).bool(message.blocked);
        /* string author_did = 3; */
        if (message.authorDid !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.authorDid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.BlockedPost
 */
export const BlockedPost = new BlockedPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ThreadViewPostInner$Type extends MessageType<ThreadViewPostInner> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner", [
            { no: 1, name: "post", kind: "message", oneof: "actualPost", T: () => TheardViewPost },
            { no: 2, name: "not_found", kind: "message", oneof: "actualPost", T: () => NotFoundPost },
            { no: 3, name: "blocked_post", kind: "message", oneof: "actualPost", T: () => BlockedPost }
        ]);
    }
    create(value?: PartialMessage<ThreadViewPostInner>): ThreadViewPostInner {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.actualPost = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ThreadViewPostInner>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ThreadViewPostInner): ThreadViewPostInner {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post */ 1:
                    message.actualPost = {
                        oneofKind: "post",
                        post: TheardViewPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).post)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found */ 2:
                    message.actualPost = {
                        oneofKind: "notFound",
                        notFound: NotFoundPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).notFound)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post */ 3:
                    message.actualPost = {
                        oneofKind: "blockedPost",
                        blockedPost: BlockedPost.internalBinaryRead(reader, reader.uint32(), options, (message.actualPost as any).blockedPost)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ThreadViewPostInner, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.TheardViewPost post = 1; */
        if (message.actualPost.oneofKind === "post")
            TheardViewPost.internalBinaryWrite(message.actualPost.post, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.NotFoundPost not_found = 2; */
        if (message.actualPost.oneofKind === "notFound")
            NotFoundPost.internalBinaryWrite(message.actualPost.notFound, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.BlockedPost blocked_post = 3; */
        if (message.actualPost.oneofKind === "blockedPost")
            BlockedPost.internalBinaryWrite(message.actualPost.blockedPost, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner
 */
export const ThreadViewPostInner = new ThreadViewPostInner$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TheardViewPost$Type extends MessageType<TheardViewPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.TheardViewPost", [
            { no: 1, name: "parent", kind: "message", T: () => ThreadViewPostInner },
            { no: 2, name: "post", kind: "message", T: () => PostViewMessage },
            { no: 3, name: "replies", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ThreadViewPostInner }
        ]);
    }
    create(value?: PartialMessage<TheardViewPost>): TheardViewPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.replies = [];
        if (value !== undefined)
            reflectionMergePartial<TheardViewPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TheardViewPost): TheardViewPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent */ 1:
                    message.parent = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.parent);
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post */ 2:
                    message.post = PostViewMessage.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies */ 3:
                    message.replies.push(ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TheardViewPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 1; */
        if (message.parent)
            ThreadViewPostInner.internalBinaryWrite(message.parent, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2; */
        if (message.post)
            PostViewMessage.internalBinaryWrite(message.post, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner replies = 3; */
        for (let i = 0; i < message.replies.length; i++)
            ThreadViewPostInner.internalBinaryWrite(message.replies[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.TheardViewPost
 */
export const TheardViewPost = new TheardViewPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewThreadResponse$Type extends MessageType<ViewThreadResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse", [
            { no: 1, name: "thread", kind: "message", T: () => ThreadViewPostInner }
        ]);
    }
    create(value?: PartialMessage<ViewThreadResponse>): ViewThreadResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ViewThreadResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewThreadResponse): ViewThreadResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner thread */ 1:
                    message.thread = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.thread);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewThreadResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner thread = 1; */
        if (message.thread)
            ThreadViewPostInner.internalBinaryWrite(message.thread, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewThreadResponse
 */
export const ViewThreadResponse = new ViewThreadResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostsRequest$Type extends MessageType<ViewPostsRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest", [
            { no: 1, name: "uri", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ViewPostsRequest>): ViewPostsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uri = [];
        if (value !== undefined)
            reflectionMergePartial<ViewPostsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostsRequest): ViewPostsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string uri */ 1:
                    message.uri.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string uri = 1; */
        for (let i = 0; i < message.uri.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.uri[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsRequest
 */
export const ViewPostsRequest = new ViewPostsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewPostsResponse$Type extends MessageType<ViewPostsResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse", [
            { no: 1, name: "posts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostViewMessage }
        ]);
    }
    create(value?: PartialMessage<ViewPostsResponse>): ViewPostsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        if (value !== undefined)
            reflectionMergePartial<ViewPostsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewPostsResponse): ViewPostsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts */ 1:
                    message.posts.push(PostViewMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewPostsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.view.PostViewMessage posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            PostViewMessage.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ViewPostsResponse
 */
export const ViewPostsResponse = new ViewPostsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplyRefMessage$Type extends MessageType<ReplyRefMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage", [
            { no: 1, name: "root", kind: "message", T: () => ThreadViewPostInner },
            { no: 2, name: "parent", kind: "message", T: () => ThreadViewPostInner },
            { no: 3, name: "grandparent_author", kind: "message", T: () => ProfileViewBasic }
        ]);
    }
    create(value?: PartialMessage<ReplyRefMessage>): ReplyRefMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReplyRefMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplyRefMessage): ReplyRefMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root */ 1:
                    message.root = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent */ 2:
                    message.parent = ThreadViewPostInner.internalBinaryRead(reader, reader.uint32(), options, message.parent);
                    break;
                case /* optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author */ 3:
                    message.grandparentAuthor = ProfileViewBasic.internalBinaryRead(reader, reader.uint32(), options, message.grandparentAuthor);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReplyRefMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner root = 1; */
        if (message.root)
            ThreadViewPostInner.internalBinaryWrite(message.root, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.view.ThreadViewPostInner parent = 2; */
        if (message.parent)
            ThreadViewPostInner.internalBinaryWrite(message.parent, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic grandparent_author = 3; */
        if (message.grandparentAuthor)
            ProfileViewBasic.internalBinaryWrite(message.grandparentAuthor, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage
 */
export const ReplyRefMessage = new ReplyRefMessage$Type();
/**
 * @generated ServiceType for protobuf service mg.tonymushah.lanitra_manga.posts.view.PostViews
 */
export const PostViews = new ServiceType("mg.tonymushah.lanitra_manga.posts.view.PostViews", [
    { name: "viewPostThread", options: {}, I: ViewPostThreadRequest, O: ViewThreadResponse },
    { name: "getPosts", options: {}, I: ViewPostsRequest, O: ViewPostsResponse }
]);
