[package]
name = "lanitra-manga-auth"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[build-dependencies]
kanamaru-build = { workspace = true, default-features = false, features = [
    "prost",
] }

[dependencies]
kanamaru = { workspace = true }
prost = { workspace = true }
bsky-sdk = { workspace = true }
atrium-api = { workspace = true }
