[package]
name = "lanitra-manga-profiles"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[build-dependencies]
lanitra-manga-proto-build.workspace = true

[dependencies]
kanamaru = { workspace = true }
prost = { workspace = true }
lanitra-manga-commons = { path = "../commons" }
bsky-sdk = { workspace = true }
atrium-api = { workspace = true }
