// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "auth.proto" (package "mg.tonymushah.lanitra_manga.auth", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.auth.LoginRequestMessage
 */
export interface LoginRequestMessage {
}
// @generated message type with reflection information, may provide speed optimized methods
class LoginRequestMessage$Type extends MessageType<LoginRequestMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.auth.LoginRequestMessage", []);
    }
    create(value?: PartialMessage<LoginRequestMessage>): LoginRequestMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LoginRequestMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRequestMessage): LoginRequestMessage {
        return target ?? this.create();
    }
    internalBinaryWrite(message: LoginRequestMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.auth.LoginRequestMessage
 */
export const LoginRequestMessage = new LoginRequestMessage$Type();
