// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "commons.proto" (package "mg.tonymushah.lanitra_manga", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.Empty
 */
export interface Empty {
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.RichText
 */
export interface RichText {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * @generated from protobuf field: optional bool detect_facets = 2;
     */
    detectFacets?: boolean;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.RichTextDetails
 */
export interface RichTextDetails {
    /**
     * @generated from protobuf field: string markdown = 1;
     */
    markdown: string;
    /**
     * @generated from protobuf field: uint64 length = 2;
     */
    length: bigint;
    /**
     * @generated from protobuf field: uint64 grapheme_length = 3;
     */
    graphemeLength: bigint;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.DateTime
 */
export interface DateTime {
    /**
     * @generated from protobuf field: string date = 1;
     */
    date: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.CommitMetadata
 */
export interface CommitMetadata {
    /**
     * @generated from protobuf field: string cid = 1;
     */
    cid: string;
    /**
     * @generated from protobuf field: string rev = 2;
     */
    rev: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.DataRef
 */
export interface DataRef {
    /**
     * @generated from protobuf field: string cid = 1;
     */
    cid: string;
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.CommitMetadata commit = 3;
     */
    commit?: CommitMetadata;
    /**
     * @generated from protobuf field: optional string validation_status = 4;
     */
    validationStatus?: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.MainData
 */
export interface MainData {
    /**
     * @generated from protobuf field: string cid = 1;
     */
    cid: string;
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Empty$Type extends MessageType<Empty> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.Empty", []);
    }
    create(value?: PartialMessage<Empty>): Empty {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Empty>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Empty): Empty {
        return target ?? this.create();
    }
    internalBinaryWrite(message: Empty, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.Empty
 */
export const Empty = new Empty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RichText$Type extends MessageType<RichText> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.RichText", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "detect_facets", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<RichText>): RichText {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<RichText>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RichText): RichText {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* optional bool detect_facets */ 2:
                    message.detectFacets = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RichText, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* optional bool detect_facets = 2; */
        if (message.detectFacets !== undefined)
            writer.tag(2, WireType.Varint).bool(message.detectFacets);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.RichText
 */
export const RichText = new RichText$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RichTextDetails$Type extends MessageType<RichTextDetails> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.RichTextDetails", [
            { no: 1, name: "markdown", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "length", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "grapheme_length", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<RichTextDetails>): RichTextDetails {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.markdown = "";
        message.length = 0n;
        message.graphemeLength = 0n;
        if (value !== undefined)
            reflectionMergePartial<RichTextDetails>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RichTextDetails): RichTextDetails {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string markdown */ 1:
                    message.markdown = reader.string();
                    break;
                case /* uint64 length */ 2:
                    message.length = reader.uint64().toBigInt();
                    break;
                case /* uint64 grapheme_length */ 3:
                    message.graphemeLength = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RichTextDetails, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string markdown = 1; */
        if (message.markdown !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.markdown);
        /* uint64 length = 2; */
        if (message.length !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.length);
        /* uint64 grapheme_length = 3; */
        if (message.graphemeLength !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.graphemeLength);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.RichTextDetails
 */
export const RichTextDetails = new RichTextDetails$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DateTime$Type extends MessageType<DateTime> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.DateTime", [
            { no: 1, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DateTime>): DateTime {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.date = "";
        if (value !== undefined)
            reflectionMergePartial<DateTime>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DateTime): DateTime {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string date */ 1:
                    message.date = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DateTime, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string date = 1; */
        if (message.date !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.date);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.DateTime
 */
export const DateTime = new DateTime$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommitMetadata$Type extends MessageType<CommitMetadata> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.CommitMetadata", [
            { no: 1, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "rev", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CommitMetadata>): CommitMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.rev = "";
        if (value !== undefined)
            reflectionMergePartial<CommitMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommitMetadata): CommitMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cid */ 1:
                    message.cid = reader.string();
                    break;
                case /* string rev */ 2:
                    message.rev = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommitMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cid = 1; */
        if (message.cid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cid);
        /* string rev = 2; */
        if (message.rev !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.rev);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.CommitMetadata
 */
export const CommitMetadata = new CommitMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataRef$Type extends MessageType<DataRef> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.DataRef", [
            { no: 1, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "commit", kind: "message", T: () => CommitMetadata },
            { no: 4, name: "validation_status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DataRef>): DataRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<DataRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataRef): DataRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cid */ 1:
                    message.cid = reader.string();
                    break;
                case /* string uri */ 2:
                    message.uri = reader.string();
                    break;
                case /* optional mg.tonymushah.lanitra_manga.CommitMetadata commit */ 3:
                    message.commit = CommitMetadata.internalBinaryRead(reader, reader.uint32(), options, message.commit);
                    break;
                case /* optional string validation_status */ 4:
                    message.validationStatus = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DataRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cid = 1; */
        if (message.cid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cid);
        /* string uri = 2; */
        if (message.uri !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uri);
        /* optional mg.tonymushah.lanitra_manga.CommitMetadata commit = 3; */
        if (message.commit)
            CommitMetadata.internalBinaryWrite(message.commit, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional string validation_status = 4; */
        if (message.validationStatus !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.validationStatus);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.DataRef
 */
export const DataRef = new DataRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MainData$Type extends MessageType<MainData> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.MainData", [
            { no: 1, name: "cid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MainData>): MainData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cid = "";
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<MainData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MainData): MainData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cid */ 1:
                    message.cid = reader.string();
                    break;
                case /* string uri */ 2:
                    message.uri = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MainData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cid = 1; */
        if (message.cid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cid);
        /* string uri = 2; */
        if (message.uri !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uri);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.MainData
 */
export const MainData = new MainData$Type();
/**
 * @generated ServiceType for protobuf service mg.tonymushah.lanitra_manga.Utils
 */
export const Utils = new ServiceType("mg.tonymushah.lanitra_manga.Utils", [
    { name: "getRichTextDetails", options: {}, I: RichText, O: RichTextDetails },
    { name: "getRichTextDetailsStream", serverStreaming: true, clientStreaming: true, options: {}, I: RichText, O: RichTextDetails }
]);
