// @generated by protobuf-ts 2.9.6 with parameter server_none
// @generated from protobuf file "commons.proto" (package "mg.tonymushah.lanitra_manga.commons", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Utils } from "./commons";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RichTextDetails } from "./commons";
import type { RichText } from "./commons";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.commons.Utils
 */
export interface IUtilsClient {
    /**
     * @generated from protobuf rpc: getRichTextDetails(mg.tonymushah.lanitra_manga.commons.RichText) returns (mg.tonymushah.lanitra_manga.commons.RichTextDetails);
     */
    getRichTextDetails(input: RichText, options?: RpcOptions): UnaryCall<RichText, RichTextDetails>;
    /**
     * @generated from protobuf rpc: getRichTextDetailsStream(stream mg.tonymushah.lanitra_manga.commons.RichText) returns (stream mg.tonymushah.lanitra_manga.commons.RichTextDetails);
     */
    getRichTextDetailsStream(options?: RpcOptions): DuplexStreamingCall<RichText, RichTextDetails>;
}
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.commons.Utils
 */
export class UtilsClient implements IUtilsClient, ServiceInfo {
    typeName = Utils.typeName;
    methods = Utils.methods;
    options = Utils.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: getRichTextDetails(mg.tonymushah.lanitra_manga.commons.RichText) returns (mg.tonymushah.lanitra_manga.commons.RichTextDetails);
     */
    getRichTextDetails(input: RichText, options?: RpcOptions): UnaryCall<RichText, RichTextDetails> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RichText, RichTextDetails>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: getRichTextDetailsStream(stream mg.tonymushah.lanitra_manga.commons.RichText) returns (stream mg.tonymushah.lanitra_manga.commons.RichTextDetails);
     */
    getRichTextDetailsStream(options?: RpcOptions): DuplexStreamingCall<RichText, RichTextDetails> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RichText, RichTextDetails>("duplex", this._transport, method, opt);
    }
}
