// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "feeds.proto" (package "mg.tonymushah.lanitra_manga.feeds", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Feeds } from "./feeds";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetTimelineResponse } from "./feeds";
import type { GetTimelineRequest } from "./feeds";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.feeds.Feeds
 */
export interface IFeedsClient {
    /**
     * @generated from protobuf rpc: getTimeline(mg.tonymushah.lanitra_manga.feeds.GetTimelineRequest) returns (mg.tonymushah.lanitra_manga.feeds.GetTimelineResponse);
     */
    getTimeline(input: GetTimelineRequest, options?: RpcOptions): UnaryCall<GetTimelineRequest, GetTimelineResponse>;
}
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.feeds.Feeds
 */
export class FeedsClient implements IFeedsClient, ServiceInfo {
    typeName = Feeds.typeName;
    methods = Feeds.methods;
    options = Feeds.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: getTimeline(mg.tonymushah.lanitra_manga.feeds.GetTimelineRequest) returns (mg.tonymushah.lanitra_manga.feeds.GetTimelineResponse);
     */
    getTimeline(input: GetTimelineRequest, options?: RpcOptions): UnaryCall<GetTimelineRequest, GetTimelineResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTimelineRequest, GetTimelineResponse>("unary", this._transport, method, opt, input);
    }
}
