// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "feeds.proto" (package "mg.tonymushah.lanitra_manga.feeds", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ReplyRefMessage } from "./posts/view";
import { PostViewMessage } from "./posts/view";
import { ProfileViewBasic } from "./profiles";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.GetTimelineRequest
 */
export interface GetTimelineRequest {
    /**
     * @generated from protobuf field: optional string algorithm = 1;
     */
    algorithm?: string;
    /**
     * @generated from protobuf field: optional string cursor = 2;
     */
    cursor?: string;
    /**
     * @generated from protobuf field: optional uint32 limit = 3;
     */
    limit?: number;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.ReasonPin
 */
export interface ReasonPin {
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.ReasonRepost
 */
export interface ReasonRepost {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic by = 1;
     */
    by?: ProfileViewBasic;
    /**
     * @generated from protobuf field: string indexed_at = 2;
     */
    indexedAt: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason
 */
export interface FeedViewPostReason {
    /**
     * @generated from protobuf oneof: reason
     */
    reason: {
        oneofKind: "repost";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.feeds.ReasonRepost repost = 1;
         */
        repost: ReasonRepost;
    } | {
        oneofKind: "pin";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.feeds.ReasonPin pin = 2;
         */
        pin: ReasonPin;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage
 */
export interface FeedViewPostMessage {
    /**
     * @generated from protobuf field: optional string feed_context = 1;
     */
    feedContext?: string;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2;
     */
    post?: PostViewMessage;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage reply = 3;
     */
    reply?: ReplyRefMessage;
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason reason = 4;
     */
    reason?: FeedViewPostReason;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.GetTimelineResponse
 */
export interface GetTimelineResponse {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed = 1;
     */
    feed: FeedViewPostMessage[];
    /**
     * @generated from protobuf field: optional string cursor = 2;
     */
    cursor?: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.GetFeedRequest
 */
export interface GetFeedRequest {
    /**
     * @generated from protobuf field: string feed = 1;
     */
    feed: string;
    /**
     * @generated from protobuf field: optional string cursor = 2;
     */
    cursor?: string;
    /**
     * @generated from protobuf field: optional uint32 limit = 3;
     */
    limit?: number;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.GetFeedResponse
 */
export interface GetFeedResponse {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed = 1;
     */
    feed: FeedViewPostMessage[];
    /**
     * @generated from protobuf field: optional string cursor = 2;
     */
    cursor?: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.feeds.GetHomeFeedRequest
 */
export interface GetHomeFeedRequest {
    /**
     * @generated from protobuf field: optional string cursor = 2;
     */
    cursor?: string;
    /**
     * @generated from protobuf field: optional uint32 limit = 3;
     */
    limit?: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetTimelineRequest$Type extends MessageType<GetTimelineRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.GetTimelineRequest", [
            { no: 1, name: "algorithm", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "limit", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetTimelineRequest>): GetTimelineRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTimelineRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTimelineRequest): GetTimelineRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string algorithm */ 1:
                    message.algorithm = reader.string();
                    break;
                case /* optional string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                case /* optional uint32 limit */ 3:
                    message.limit = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTimelineRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string algorithm = 1; */
        if (message.algorithm !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.algorithm);
        /* optional string cursor = 2; */
        if (message.cursor !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        /* optional uint32 limit = 3; */
        if (message.limit !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.GetTimelineRequest
 */
export const GetTimelineRequest = new GetTimelineRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReasonPin$Type extends MessageType<ReasonPin> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.ReasonPin", []);
    }
    create(value?: PartialMessage<ReasonPin>): ReasonPin {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReasonPin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReasonPin): ReasonPin {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ReasonPin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.ReasonPin
 */
export const ReasonPin = new ReasonPin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReasonRepost$Type extends MessageType<ReasonRepost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.ReasonRepost", [
            { no: 1, name: "by", kind: "message", T: () => ProfileViewBasic },
            { no: 2, name: "indexed_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReasonRepost>): ReasonRepost {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.indexedAt = "";
        if (value !== undefined)
            reflectionMergePartial<ReasonRepost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReasonRepost): ReasonRepost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic by */ 1:
                    message.by = ProfileViewBasic.internalBinaryRead(reader, reader.uint32(), options, message.by);
                    break;
                case /* string indexed_at */ 2:
                    message.indexedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReasonRepost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic by = 1; */
        if (message.by)
            ProfileViewBasic.internalBinaryWrite(message.by, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string indexed_at = 2; */
        if (message.indexedAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.indexedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.ReasonRepost
 */
export const ReasonRepost = new ReasonRepost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FeedViewPostReason$Type extends MessageType<FeedViewPostReason> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason", [
            { no: 1, name: "repost", kind: "message", oneof: "reason", T: () => ReasonRepost },
            { no: 2, name: "pin", kind: "message", oneof: "reason", T: () => ReasonPin }
        ]);
    }
    create(value?: PartialMessage<FeedViewPostReason>): FeedViewPostReason {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reason = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<FeedViewPostReason>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FeedViewPostReason): FeedViewPostReason {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.feeds.ReasonRepost repost */ 1:
                    message.reason = {
                        oneofKind: "repost",
                        repost: ReasonRepost.internalBinaryRead(reader, reader.uint32(), options, (message.reason as any).repost)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.feeds.ReasonPin pin */ 2:
                    message.reason = {
                        oneofKind: "pin",
                        pin: ReasonPin.internalBinaryRead(reader, reader.uint32(), options, (message.reason as any).pin)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FeedViewPostReason, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.feeds.ReasonRepost repost = 1; */
        if (message.reason.oneofKind === "repost")
            ReasonRepost.internalBinaryWrite(message.reason.repost, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.feeds.ReasonPin pin = 2; */
        if (message.reason.oneofKind === "pin")
            ReasonPin.internalBinaryWrite(message.reason.pin, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason
 */
export const FeedViewPostReason = new FeedViewPostReason$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FeedViewPostMessage$Type extends MessageType<FeedViewPostMessage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage", [
            { no: 1, name: "feed_context", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "post", kind: "message", T: () => PostViewMessage },
            { no: 3, name: "reply", kind: "message", T: () => ReplyRefMessage },
            { no: 4, name: "reason", kind: "message", T: () => FeedViewPostReason }
        ]);
    }
    create(value?: PartialMessage<FeedViewPostMessage>): FeedViewPostMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<FeedViewPostMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FeedViewPostMessage): FeedViewPostMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string feed_context */ 1:
                    message.feedContext = reader.string();
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post */ 2:
                    message.post = PostViewMessage.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                case /* optional mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage reply */ 3:
                    message.reply = ReplyRefMessage.internalBinaryRead(reader, reader.uint32(), options, message.reply);
                    break;
                case /* optional mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason reason */ 4:
                    message.reason = FeedViewPostReason.internalBinaryRead(reader, reader.uint32(), options, message.reason);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FeedViewPostMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string feed_context = 1; */
        if (message.feedContext !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.feedContext);
        /* mg.tonymushah.lanitra_manga.posts.view.PostViewMessage post = 2; */
        if (message.post)
            PostViewMessage.internalBinaryWrite(message.post, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional mg.tonymushah.lanitra_manga.posts.view.ReplyRefMessage reply = 3; */
        if (message.reply)
            ReplyRefMessage.internalBinaryWrite(message.reply, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional mg.tonymushah.lanitra_manga.feeds.FeedViewPostReason reason = 4; */
        if (message.reason)
            FeedViewPostReason.internalBinaryWrite(message.reason, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage
 */
export const FeedViewPostMessage = new FeedViewPostMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTimelineResponse$Type extends MessageType<GetTimelineResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.GetTimelineResponse", [
            { no: 1, name: "feed", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => FeedViewPostMessage },
            { no: 2, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTimelineResponse>): GetTimelineResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.feed = [];
        if (value !== undefined)
            reflectionMergePartial<GetTimelineResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTimelineResponse): GetTimelineResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed */ 1:
                    message.feed.push(FeedViewPostMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTimelineResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed = 1; */
        for (let i = 0; i < message.feed.length; i++)
            FeedViewPostMessage.internalBinaryWrite(message.feed[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional string cursor = 2; */
        if (message.cursor !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.GetTimelineResponse
 */
export const GetTimelineResponse = new GetTimelineResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFeedRequest$Type extends MessageType<GetFeedRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.GetFeedRequest", [
            { no: 1, name: "feed", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "limit", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetFeedRequest>): GetFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.feed = "";
        if (value !== undefined)
            reflectionMergePartial<GetFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFeedRequest): GetFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string feed */ 1:
                    message.feed = reader.string();
                    break;
                case /* optional string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                case /* optional uint32 limit */ 3:
                    message.limit = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string feed = 1; */
        if (message.feed !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.feed);
        /* optional string cursor = 2; */
        if (message.cursor !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        /* optional uint32 limit = 3; */
        if (message.limit !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.GetFeedRequest
 */
export const GetFeedRequest = new GetFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFeedResponse$Type extends MessageType<GetFeedResponse> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.GetFeedResponse", [
            { no: 1, name: "feed", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => FeedViewPostMessage },
            { no: 2, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetFeedResponse>): GetFeedResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.feed = [];
        if (value !== undefined)
            reflectionMergePartial<GetFeedResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFeedResponse): GetFeedResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed */ 1:
                    message.feed.push(FeedViewPostMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFeedResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.feeds.FeedViewPostMessage feed = 1; */
        for (let i = 0; i < message.feed.length; i++)
            FeedViewPostMessage.internalBinaryWrite(message.feed[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional string cursor = 2; */
        if (message.cursor !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.GetFeedResponse
 */
export const GetFeedResponse = new GetFeedResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetHomeFeedRequest$Type extends MessageType<GetHomeFeedRequest> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.feeds.GetHomeFeedRequest", [
            { no: 2, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "limit", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetHomeFeedRequest>): GetHomeFeedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetHomeFeedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetHomeFeedRequest): GetHomeFeedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                case /* optional uint32 limit */ 3:
                    message.limit = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetHomeFeedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string cursor = 2; */
        if (message.cursor !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        /* optional uint32 limit = 3; */
        if (message.limit !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.feeds.GetHomeFeedRequest
 */
export const GetHomeFeedRequest = new GetHomeFeedRequest$Type();
/**
 * @generated ServiceType for protobuf service mg.tonymushah.lanitra_manga.feeds.Feeds
 */
export const Feeds = new ServiceType("mg.tonymushah.lanitra_manga.feeds.Feeds", [
    { name: "getTimeline", options: {}, I: GetTimelineRequest, O: GetTimelineResponse },
    { name: "getFeed", options: {}, I: GetFeedRequest, O: GetFeedResponse },
    { name: "getHomeFeed", options: {}, I: GetHomeFeedRequest, O: GetFeedResponse }
]);
