// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "posts.proto" (package "mg.tonymushah.lanitra_manga.posts", syntax proto3)
// tslint:disable
import { Empty } from "./commons";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { DataRef } from "./commons";
import { RichText } from "./commons";
import { MainData } from "./commons";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededImage
 */
export interface EmbededImage {
    /**
     * @generated from protobuf field: string alt = 1;
     */
    alt: string;
    /**
     * @generated from protobuf field: string path = 2;
     */
    path: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededImages
 */
export interface EmbededImages {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.EmbededImage images = 1;
     */
    images: EmbededImage[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededVideo
 */
export interface EmbededVideo {
    /**
     * @generated from protobuf field: optional string alt = 1;
     */
    alt?: string;
    /**
     * @generated from protobuf field: string path = 2;
     */
    path: string;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededVideos
 */
export interface EmbededVideos {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.EmbededVideo videos = 1;
     */
    videos: EmbededVideo[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededExternal
 */
export interface EmbededExternal {
    /**
     * @generated from protobuf field: string description = 1;
     */
    description: string;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string uri = 3;
     */
    uri: string;
    /**
     * @generated from protobuf field: optional bool include_thumb = 4;
     */
    includeThumb?: boolean;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededExternals
 */
export interface EmbededExternals {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededExternal externals = 1;
     */
    externals?: EmbededExternal;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPost
 */
export interface EmbededPost {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.MainData post = 1;
     */
    post?: MainData;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPosts
 */
export interface EmbededPosts {
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.EmbededPost posts = 1;
     */
    posts: EmbededPost[];
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia
 */
export interface EmbededPostWithMedia {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.MainData post = 1;
     */
    post?: MainData;
    /**
     * @generated from protobuf oneof: media
     */
    media: {
        oneofKind: "images";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededImages images = 2;
         */
        images: EmbededImages;
    } | {
        oneofKind: "externals";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededExternals externals = 3;
         */
        externals: EmbededExternals;
    } | {
        oneofKind: "videos";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededVideos videos = 4;
         */
        videos: EmbededVideos;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias
 */
export interface EmbededPostWithMedias {
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia posts_with_medias = 1;
     */
    postsWithMedias?: EmbededPostWithMedia;
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.PostRecord
 */
export interface PostRecord {
    /**
     * @generated from protobuf field: optional string datetime = 1;
     */
    datetime?: string;
    /**
     * @generated from protobuf field: mg.tonymushah.lanitra_manga.RichText text = 2;
     */
    text?: RichText;
    /**
     * @generated from protobuf field: repeated mg.tonymushah.lanitra_manga.posts.PostRecord replies = 3;
     */
    replies: PostRecord[];
    /**
     * @generated from protobuf oneof: embeded
     */
    embeded: {
        oneofKind: "images";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededImages images = 4;
         */
        images: EmbededImages;
    } | {
        oneofKind: "externals";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededExternals externals = 5;
         */
        externals: EmbededExternals;
    } | {
        oneofKind: "videos";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededVideos videos = 6;
         */
        videos: EmbededVideos;
    } | {
        oneofKind: "posts";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededPosts posts = 7;
         */
        posts: EmbededPosts;
    } | {
        oneofKind: "postsWithMedias";
        /**
         * @generated from protobuf field: mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias posts_with_medias = 8;
         */
        postsWithMedias: EmbededPostWithMedias;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.posts.ClearPostsServiceResponses
 */
export interface ClearPostsServiceResponses {
    /**
     * @generated from protobuf field: optional mg.tonymushah.lanitra_manga.DataRef root = 1;
     */
    root?: DataRef;
}
// @generated message type with reflection information, may provide speed optimized methods
class EmbededImage$Type extends MessageType<EmbededImage> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededImage", [
            { no: 1, name: "alt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EmbededImage>): EmbededImage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.alt = "";
        message.path = "";
        if (value !== undefined)
            reflectionMergePartial<EmbededImage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededImage): EmbededImage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string alt */ 1:
                    message.alt = reader.string();
                    break;
                case /* string path */ 2:
                    message.path = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededImage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string alt = 1; */
        if (message.alt !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.alt);
        /* string path = 2; */
        if (message.path !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.path);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededImage
 */
export const EmbededImage = new EmbededImage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededImages$Type extends MessageType<EmbededImages> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededImages", [
            { no: 1, name: "images", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => EmbededImage }
        ]);
    }
    create(value?: PartialMessage<EmbededImages>): EmbededImages {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.images = [];
        if (value !== undefined)
            reflectionMergePartial<EmbededImages>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededImages): EmbededImages {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.EmbededImage images */ 1:
                    message.images.push(EmbededImage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededImages, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.EmbededImage images = 1; */
        for (let i = 0; i < message.images.length; i++)
            EmbededImage.internalBinaryWrite(message.images[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededImages
 */
export const EmbededImages = new EmbededImages$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededVideo$Type extends MessageType<EmbededVideo> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededVideo", [
            { no: 1, name: "alt", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EmbededVideo>): EmbededVideo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.path = "";
        if (value !== undefined)
            reflectionMergePartial<EmbededVideo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededVideo): EmbededVideo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string alt */ 1:
                    message.alt = reader.string();
                    break;
                case /* string path */ 2:
                    message.path = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededVideo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string alt = 1; */
        if (message.alt !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.alt);
        /* string path = 2; */
        if (message.path !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.path);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededVideo
 */
export const EmbededVideo = new EmbededVideo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededVideos$Type extends MessageType<EmbededVideos> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededVideos", [
            { no: 1, name: "videos", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => EmbededVideo }
        ]);
    }
    create(value?: PartialMessage<EmbededVideos>): EmbededVideos {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.videos = [];
        if (value !== undefined)
            reflectionMergePartial<EmbededVideos>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededVideos): EmbededVideos {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.EmbededVideo videos */ 1:
                    message.videos.push(EmbededVideo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededVideos, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.EmbededVideo videos = 1; */
        for (let i = 0; i < message.videos.length; i++)
            EmbededVideo.internalBinaryWrite(message.videos[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededVideos
 */
export const EmbededVideos = new EmbededVideos$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededExternal$Type extends MessageType<EmbededExternal> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededExternal", [
            { no: 1, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "include_thumb", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<EmbededExternal>): EmbededExternal {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.description = "";
        message.title = "";
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial<EmbededExternal>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededExternal): EmbededExternal {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string description */ 1:
                    message.description = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string uri */ 3:
                    message.uri = reader.string();
                    break;
                case /* optional bool include_thumb */ 4:
                    message.includeThumb = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededExternal, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string description = 1; */
        if (message.description !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.description);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string uri = 3; */
        if (message.uri !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.uri);
        /* optional bool include_thumb = 4; */
        if (message.includeThumb !== undefined)
            writer.tag(4, WireType.Varint).bool(message.includeThumb);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededExternal
 */
export const EmbededExternal = new EmbededExternal$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededExternals$Type extends MessageType<EmbededExternals> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededExternals", [
            { no: 1, name: "externals", kind: "message", T: () => EmbededExternal }
        ]);
    }
    create(value?: PartialMessage<EmbededExternals>): EmbededExternals {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EmbededExternals>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededExternals): EmbededExternals {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.EmbededExternal externals */ 1:
                    message.externals = EmbededExternal.internalBinaryRead(reader, reader.uint32(), options, message.externals);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededExternals, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.EmbededExternal externals = 1; */
        if (message.externals)
            EmbededExternal.internalBinaryWrite(message.externals, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededExternals
 */
export const EmbededExternals = new EmbededExternals$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededPost$Type extends MessageType<EmbededPost> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededPost", [
            { no: 1, name: "post", kind: "message", T: () => MainData }
        ]);
    }
    create(value?: PartialMessage<EmbededPost>): EmbededPost {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EmbededPost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededPost): EmbededPost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.MainData post */ 1:
                    message.post = MainData.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededPost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.MainData post = 1; */
        if (message.post)
            MainData.internalBinaryWrite(message.post, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPost
 */
export const EmbededPost = new EmbededPost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededPosts$Type extends MessageType<EmbededPosts> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededPosts", [
            { no: 1, name: "posts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => EmbededPost }
        ]);
    }
    create(value?: PartialMessage<EmbededPosts>): EmbededPosts {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.posts = [];
        if (value !== undefined)
            reflectionMergePartial<EmbededPosts>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededPosts): EmbededPosts {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated mg.tonymushah.lanitra_manga.posts.EmbededPost posts */ 1:
                    message.posts.push(EmbededPost.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededPosts, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated mg.tonymushah.lanitra_manga.posts.EmbededPost posts = 1; */
        for (let i = 0; i < message.posts.length; i++)
            EmbededPost.internalBinaryWrite(message.posts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPosts
 */
export const EmbededPosts = new EmbededPosts$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededPostWithMedia$Type extends MessageType<EmbededPostWithMedia> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia", [
            { no: 1, name: "post", kind: "message", T: () => MainData },
            { no: 2, name: "images", kind: "message", oneof: "media", T: () => EmbededImages },
            { no: 3, name: "externals", kind: "message", oneof: "media", T: () => EmbededExternals },
            { no: 4, name: "videos", kind: "message", oneof: "media", T: () => EmbededVideos }
        ]);
    }
    create(value?: PartialMessage<EmbededPostWithMedia>): EmbededPostWithMedia {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.media = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<EmbededPostWithMedia>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededPostWithMedia): EmbededPostWithMedia {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.MainData post */ 1:
                    message.post = MainData.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededImages images */ 2:
                    message.media = {
                        oneofKind: "images",
                        images: EmbededImages.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).images)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededExternals externals */ 3:
                    message.media = {
                        oneofKind: "externals",
                        externals: EmbededExternals.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).externals)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededVideos videos */ 4:
                    message.media = {
                        oneofKind: "videos",
                        videos: EmbededVideos.internalBinaryRead(reader, reader.uint32(), options, (message.media as any).videos)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededPostWithMedia, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.MainData post = 1; */
        if (message.post)
            MainData.internalBinaryWrite(message.post, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededImages images = 2; */
        if (message.media.oneofKind === "images")
            EmbededImages.internalBinaryWrite(message.media.images, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededExternals externals = 3; */
        if (message.media.oneofKind === "externals")
            EmbededExternals.internalBinaryWrite(message.media.externals, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededVideos videos = 4; */
        if (message.media.oneofKind === "videos")
            EmbededVideos.internalBinaryWrite(message.media.videos, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia
 */
export const EmbededPostWithMedia = new EmbededPostWithMedia$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmbededPostWithMedias$Type extends MessageType<EmbededPostWithMedias> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias", [
            { no: 1, name: "posts_with_medias", kind: "message", T: () => EmbededPostWithMedia }
        ]);
    }
    create(value?: PartialMessage<EmbededPostWithMedias>): EmbededPostWithMedias {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EmbededPostWithMedias>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmbededPostWithMedias): EmbededPostWithMedias {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia posts_with_medias */ 1:
                    message.postsWithMedias = EmbededPostWithMedia.internalBinaryRead(reader, reader.uint32(), options, message.postsWithMedias);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmbededPostWithMedias, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedia posts_with_medias = 1; */
        if (message.postsWithMedias)
            EmbededPostWithMedia.internalBinaryWrite(message.postsWithMedias, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias
 */
export const EmbededPostWithMedias = new EmbededPostWithMedias$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostRecord$Type extends MessageType<PostRecord> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.PostRecord", [
            { no: 1, name: "datetime", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "text", kind: "message", T: () => RichText },
            { no: 3, name: "replies", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PostRecord },
            { no: 4, name: "images", kind: "message", oneof: "embeded", T: () => EmbededImages },
            { no: 5, name: "externals", kind: "message", oneof: "embeded", T: () => EmbededExternals },
            { no: 6, name: "videos", kind: "message", oneof: "embeded", T: () => EmbededVideos },
            { no: 7, name: "posts", kind: "message", oneof: "embeded", T: () => EmbededPosts },
            { no: 8, name: "posts_with_medias", kind: "message", oneof: "embeded", T: () => EmbededPostWithMedias }
        ]);
    }
    create(value?: PartialMessage<PostRecord>): PostRecord {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.replies = [];
        message.embeded = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<PostRecord>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostRecord): PostRecord {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string datetime */ 1:
                    message.datetime = reader.string();
                    break;
                case /* mg.tonymushah.lanitra_manga.RichText text */ 2:
                    message.text = RichText.internalBinaryRead(reader, reader.uint32(), options, message.text);
                    break;
                case /* repeated mg.tonymushah.lanitra_manga.posts.PostRecord replies */ 3:
                    message.replies.push(PostRecord.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededImages images */ 4:
                    message.embeded = {
                        oneofKind: "images",
                        images: EmbededImages.internalBinaryRead(reader, reader.uint32(), options, (message.embeded as any).images)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededExternals externals */ 5:
                    message.embeded = {
                        oneofKind: "externals",
                        externals: EmbededExternals.internalBinaryRead(reader, reader.uint32(), options, (message.embeded as any).externals)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededVideos videos */ 6:
                    message.embeded = {
                        oneofKind: "videos",
                        videos: EmbededVideos.internalBinaryRead(reader, reader.uint32(), options, (message.embeded as any).videos)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededPosts posts */ 7:
                    message.embeded = {
                        oneofKind: "posts",
                        posts: EmbededPosts.internalBinaryRead(reader, reader.uint32(), options, (message.embeded as any).posts)
                    };
                    break;
                case /* mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias posts_with_medias */ 8:
                    message.embeded = {
                        oneofKind: "postsWithMedias",
                        postsWithMedias: EmbededPostWithMedias.internalBinaryRead(reader, reader.uint32(), options, (message.embeded as any).postsWithMedias)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostRecord, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string datetime = 1; */
        if (message.datetime !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.datetime);
        /* mg.tonymushah.lanitra_manga.RichText text = 2; */
        if (message.text)
            RichText.internalBinaryWrite(message.text, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated mg.tonymushah.lanitra_manga.posts.PostRecord replies = 3; */
        for (let i = 0; i < message.replies.length; i++)
            PostRecord.internalBinaryWrite(message.replies[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededImages images = 4; */
        if (message.embeded.oneofKind === "images")
            EmbededImages.internalBinaryWrite(message.embeded.images, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededExternals externals = 5; */
        if (message.embeded.oneofKind === "externals")
            EmbededExternals.internalBinaryWrite(message.embeded.externals, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededVideos videos = 6; */
        if (message.embeded.oneofKind === "videos")
            EmbededVideos.internalBinaryWrite(message.embeded.videos, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededPosts posts = 7; */
        if (message.embeded.oneofKind === "posts")
            EmbededPosts.internalBinaryWrite(message.embeded.posts, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* mg.tonymushah.lanitra_manga.posts.EmbededPostWithMedias posts_with_medias = 8; */
        if (message.embeded.oneofKind === "postsWithMedias")
            EmbededPostWithMedias.internalBinaryWrite(message.embeded.postsWithMedias, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.PostRecord
 */
export const PostRecord = new PostRecord$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClearPostsServiceResponses$Type extends MessageType<ClearPostsServiceResponses> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.posts.ClearPostsServiceResponses", [
            { no: 1, name: "root", kind: "message", T: () => DataRef }
        ]);
    }
    create(value?: PartialMessage<ClearPostsServiceResponses>): ClearPostsServiceResponses {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ClearPostsServiceResponses>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClearPostsServiceResponses): ClearPostsServiceResponses {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional mg.tonymushah.lanitra_manga.DataRef root */ 1:
                    message.root = DataRef.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClearPostsServiceResponses, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional mg.tonymushah.lanitra_manga.DataRef root = 1; */
        if (message.root)
            DataRef.internalBinaryWrite(message.root, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.posts.ClearPostsServiceResponses
 */
export const ClearPostsServiceResponses = new ClearPostsServiceResponses$Type();
/**
 * @generated ServiceType for protobuf service mg.tonymushah.lanitra_manga.posts.PostsService
 */
export const PostsService = new ServiceType("mg.tonymushah.lanitra_manga.posts.PostsService", [
    { name: "post", options: {}, I: PostRecord, O: DataRef },
    { name: "replyToLastPost", clientStreaming: true, options: {}, I: PostRecord, O: DataRef },
    { name: "makeThreadStream", clientStreaming: true, options: {}, I: PostRecord, O: DataRef },
    { name: "clear", options: {}, I: Empty, O: ClearPostsServiceResponses }
]);
