// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "posts.proto" (package "mg.tonymushah.lanitra_manga.posts", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PostsService } from "./posts";
import type { ClearPostsServiceResponses } from "./posts";
import type { Empty } from "./commons";
import type { ClientStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DataRef } from "./commons";
import type { PostRecord } from "./posts";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.posts.PostsService
 */
export interface IPostsServiceClient {
    /**
     * @generated from protobuf rpc: post(mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    post(input: PostRecord, options?: RpcOptions): UnaryCall<PostRecord, DataRef>;
    /**
     * @generated from protobuf rpc: replyToLastPost(stream mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    replyToLastPost(options?: RpcOptions): ClientStreamingCall<PostRecord, DataRef>;
    /**
     * @generated from protobuf rpc: makeThreadStream(stream mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    makeThreadStream(options?: RpcOptions): ClientStreamingCall<PostRecord, DataRef>;
    /**
     * @generated from protobuf rpc: clear(mg.tonymushah.lanitra_manga.Empty) returns (mg.tonymushah.lanitra_manga.posts.ClearPostsServiceResponses);
     */
    clear(input: Empty, options?: RpcOptions): UnaryCall<Empty, ClearPostsServiceResponses>;
}
/**
 * @generated from protobuf service mg.tonymushah.lanitra_manga.posts.PostsService
 */
export class PostsServiceClient implements IPostsServiceClient, ServiceInfo {
    typeName = PostsService.typeName;
    methods = PostsService.methods;
    options = PostsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: post(mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    post(input: PostRecord, options?: RpcOptions): UnaryCall<PostRecord, DataRef> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostRecord, DataRef>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: replyToLastPost(stream mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    replyToLastPost(options?: RpcOptions): ClientStreamingCall<PostRecord, DataRef> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostRecord, DataRef>("clientStreaming", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: makeThreadStream(stream mg.tonymushah.lanitra_manga.posts.PostRecord) returns (mg.tonymushah.lanitra_manga.DataRef);
     */
    makeThreadStream(options?: RpcOptions): ClientStreamingCall<PostRecord, DataRef> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostRecord, DataRef>("clientStreaming", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: clear(mg.tonymushah.lanitra_manga.Empty) returns (mg.tonymushah.lanitra_manga.posts.ClearPostsServiceResponses);
     */
    clear(input: Empty, options?: RpcOptions): UnaryCall<Empty, ClearPostsServiceResponses> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ClearPostsServiceResponses>("unary", this._transport, method, opt, input);
    }
}
