// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "profiles.proto" (package "mg.tonymushah.lanitra_manga.profiles", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic
 */
export interface ProfileViewBasic {
    /**
     * @generated from protobuf field: string did = 1;
     */
    did: string;
    /**
     * @generated from protobuf field: string handle = 2;
     */
    handle: string;
    /**
     * @generated from protobuf field: optional string display_name = 3;
     */
    displayName?: string;
    /**
     * @generated from protobuf field: optional string created_at = 4;
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string avatar = 5;
     */
    avatar?: string;
    /**
     * @generated from protobuf field: optional string description = 6;
     */
    description?: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ProfileViewBasic$Type extends MessageType<ProfileViewBasic> {
    constructor() {
        super("mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic", [
            { no: 1, name: "did", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "display_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "avatar", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ProfileViewBasic>): ProfileViewBasic {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.did = "";
        message.handle = "";
        if (value !== undefined)
            reflectionMergePartial<ProfileViewBasic>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProfileViewBasic): ProfileViewBasic {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string did */ 1:
                    message.did = reader.string();
                    break;
                case /* string handle */ 2:
                    message.handle = reader.string();
                    break;
                case /* optional string display_name */ 3:
                    message.displayName = reader.string();
                    break;
                case /* optional string created_at */ 4:
                    message.createdAt = reader.string();
                    break;
                case /* optional string avatar */ 5:
                    message.avatar = reader.string();
                    break;
                case /* optional string description */ 6:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProfileViewBasic, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string did = 1; */
        if (message.did !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.did);
        /* string handle = 2; */
        if (message.handle !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.handle);
        /* optional string display_name = 3; */
        if (message.displayName !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.displayName);
        /* optional string created_at = 4; */
        if (message.createdAt !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.createdAt);
        /* optional string avatar = 5; */
        if (message.avatar !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.avatar);
        /* optional string description = 6; */
        if (message.description !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mg.tonymushah.lanitra_manga.profiles.ProfileViewBasic
 */
export const ProfileViewBasic = new ProfileViewBasic$Type();
