// @generated by protobuf-ts 2.9.4 with parameter server_none
// @generated from protobuf file "myprotos.proto" (package "mg.tonymushah.kanamaru.example1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HelloService } from "./myprotos";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloResponse } from "./myprotos";
import type { HelloRequest } from "./myprotos";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mg.tonymushah.kanamaru.example1.HelloService
 */
export interface IHelloServiceClient {
    /**
     * @generated from protobuf rpc: sayHello(mg.tonymushah.kanamaru.example1.HelloRequest) returns (mg.tonymushah.kanamaru.example1.HelloResponse);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloResponse>;
}
/**
 * @generated from protobuf service mg.tonymushah.kanamaru.example1.HelloService
 */
export class HelloServiceClient implements IHelloServiceClient, ServiceInfo {
    typeName = HelloService.typeName;
    methods = HelloService.methods;
    options = HelloService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: sayHello(mg.tonymushah.kanamaru.example1.HelloRequest) returns (mg.tonymushah.kanamaru.example1.HelloResponse);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloResponse>("unary", this._transport, method, opt, input);
    }
}
